#!/bin/bash
# Generated by Orchestrator Planner — plan-20260221-063148
# Launches 4 slaves in tmux windows for parallel execution
#
# Slave 1: Senior Reviewer → code-review-123 (ptu-rule-058 P1)
# Slave 2: Game Logic Reviewer → rules-review-113 (ptu-rule-058 P1)
# Slave 3: Developer → ptu-rule-060 P0 (level budget calculation)
# Slave 4: Developer → ptu-rule-077 (Focus Speed initiative/evasion)
#
# Merge order: 1, 2, 4, 3
#
# Usage: bash scripts/launch-slaves.sh

set -e

WD="$(cd "$(dirname "$0")/.." && pwd)"
SESSION="slaves"
PLAN=".worktrees/slave-plan.json"

if [ ! -f "$WD/$PLAN" ]; then
  echo "ERROR: No slave plan found at $PLAN"
  echo "Run /survey then /plan_slaves first."
  exit 1
fi

N=$(python3 -c "import json; print(json.load(open('$WD/$PLAN'))['total_slaves'])")

echo "=== Master/Slave Orchestration ==="
echo "Plan: plan-20260221-063148"
echo "Launching $N slaves..."

# Kill existing session if present
tmux kill-session -t "$SESSION" 2>/dev/null || true

# Helper: send text to a tmux pane, then press Enter
send_and_submit() {
  local target="$1"
  local text="$2"
  tmux send-keys -t "$target" -l "$text"
  sleep 0.5
  # Send raw carriage return byte (0x0D = Enter keypress)
  tmux send-keys -t "$target" -H 0D
}

# Create session with first window
tmux new-session -d -s "$SESSION" -n "slave-1" -c "$WD"

# Create remaining windows
for i in $(seq 2 $N); do
  tmux new-window -t "$SESSION" -n "slave-$i" -c "$WD"
done

# Launch claude in all windows
for i in $(seq 1 $N); do
  send_and_submit "$SESSION:slave-$i" "unset CLAUDECODE && claude"
done

echo "[1/2] Claude instances starting in $N windows..."
echo "Waiting 30s for Claude to initialize..."
sleep 30

# Send /slave N command to each window
for i in $(seq 1 $N); do
  send_and_submit "$SESSION:slave-$i" "/slave $i"
done

echo "[2/2] All $N slaves launched!"

# Notify Imp (non-blocking — exit 0 even if daemon is down)
node "$WD/scripts/imp/notify.mjs" slaves_launched "{\"total\":$N}" 2>/dev/null || true
echo ""
echo "Session: $SESSION"
echo "Slaves: 1 through $N"
echo ""
echo "Commands:"
echo "  tmux attach -t $SESSION          # attach to session"
echo "  Ctrl-b n / Ctrl-b p              # next/prev window"
echo "  Ctrl-b <number>                  # jump to window by index"
echo "  Ctrl-b d                         # detach without killing"
echo ""
echo "When all slaves complete, run /collect_slaves to merge results."
